version: '3.7'

services:
  composer:
    image: composer
    command: [ "sleep", "infinity" ]
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app

  php:
    image: php:8.0-fpm
    build: .conf/php/
    restart: always
    expose:
      - 9001
    volumes:
      - .:/app
      - .conf/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .conf/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - .conf/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /app

  phpunit:
    image: php:8.0-fpm
    volumes:
      - .:/app
    working_dir: /app

  fpm:
    image: php:8.0-fpm
    build: .conf/php-fpm/
    restart: always
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./var/log/nginx:/var/log/nginx
      - .conf/nginx/default.conf:/etc/nginx/conf.d/default.conf

  mariadb:
    image: mariadb:latest
    ports:
      - "3307:3306"
    volumes:
      - mariadb-volume:/var/lib/mysql
      - ./mysql/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'test-db'

volumes:
  mariadb-volume:
